import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

test('finds an undated author text and saves its editorial songbook without inventing a release', async ({ page }, testInfo) => {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.goto('/search?q=The%20Derivative%20Song&type=songs');
  const card = page.locator('.catalog-card').filter({ has: page.getByRole('heading', { name: 'The Derivative Song (dy/dx)', exact: true }) });
  await expect(card).toHaveCount(1);
  await expect(card).toContainText('Undated text');
  await card.click();
  await expect(page.getByRole('heading', { level: 1, name: 'The Derivative Song (dy/dx)', exact: true })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(9);
  await expect(page.locator('.lyric-facts')).toContainText('Undated text');
  const textSchema = await page.locator('script[type="application/ld+json"]').evaluateAll((scripts) => scripts.map((script) => JSON.parse(script.textContent || '{}')).find((data) => data.name === 'The Derivative Song (dy/dx)'));
  expect(textSchema['@type']).toBe('MusicComposition');
  expect(textSchema).not.toHaveProperty('datePublished');
  await page.locator('.back-link').click();
  await expect(page.getByRole('heading', { level: 1, name: 'Tom Lehrer: Author Lyric Sheets', exact: true })).toBeVisible();
  await expect(page.locator('.album-hero')).toContainText('Songbook · Author-published texts · 44 texts');
  await expect(page.locator('.track-list ol li')).toHaveCount(44);
  await expect(page.locator('.track-list .availability--full')).toHaveCount(44);
  const bookSchema = await page.locator('script[type="application/ld+json"]').evaluateAll((scripts) => scripts.map((script) => JSON.parse(script.textContent || '{}')).find((data) => data.name === 'Tom Lehrer: Author Lyric Sheets'));
  expect(bookSchema['@type']).toBe('CreativeWorkSeries');
  expect(bookSchema).not.toHaveProperty('datePublished');
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.screenshot({ path: `test-results/author-songbook-${testInfo.project.name}.png` });
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Saved', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.goto('/saved');
  await page.reload();
  await page.getByRole('button', { name: 'Albums', exact: true }).click();
  await page.locator('.catalog-card').filter({ has: page.getByRole('heading', { name: 'Tom Lehrer: Author Lyric Sheets', exact: true }) }).click();
  await expect(page.getByRole('button', { name: 'Saved', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.locator('.back-link').click();
  await expect(page.getByRole('heading', { level: 1, name: 'Tom Lehrer', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Releases and songbooks.', exact: true })).toBeVisible();
  await expect(page.locator('.artist-hero__image img')).toHaveAttribute('src', /^\/artwork\/imported\//);
  expect(pageErrors).toEqual([]);
});

test('reads all student parts and repeated choruses from an author sheet after a deep-link refresh', async ({ page }, testInfo) => {
  await page.goto('/lyrics/tom-lehrer-dont-major-in-physics');
  await page.reload();
  await page.locator('html[data-app-ready="true"]').waitFor();
  await expect(page.getByRole('heading', { level: 1, name: "Don't Major in Physics", exact: true })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(36);
  await page.getByRole('button', { name: /Chorus 3$/ }).click();
  await expect(page.locator('#section-6')).toBeInViewport();
  expect(await page.locator('#section-6 > p').allTextContents()).toEqual(await page.locator('#section-2 > p').allTextContents());
  await expect(page.getByRole('link', { name: 'Read the author’s lyric sheet (PDF)' })).toHaveAttribute('href', /dont-major-in-physics.pdf$/);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => localStorage.setItem('test:copied', text) } }));
  await page.getByRole('button', { name: 'Copy lyrics', exact: true }).click();
  await expect(page.getByText('Lyrics copied', { exact: true })).toBeVisible();
  const copied = await page.evaluate(() => localStorage.getItem('test:copied'));
  expect(copied).toContain('[Third student]');
  expect(copied).toContain('[Chorus 3]');
  expect(copied).toContain('Public-domain text via Tom Lehrer:');
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.locator('#section-1').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/author-sheet-${testInfo.project.name}.png` });
});

test('opens a local artist photo, sourced album edition and real track without pseudo lyrics', async ({ page }) => {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.goto('/artists/adele');
  await page.locator('html[data-app-ready="true"]').waitFor();
  const portrait = page.locator('.artist-hero__image img');
  await expect(portrait).toHaveAttribute('src', /^\/artwork\/imported\//);
  await expect.poll(() => portrait.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true);
  await expect(page.getByText(/Photo:/)).toBeVisible();
  await expect(page.getByRole('link', { name: 'MusicBrainz', exact: true })).toHaveAttribute('href', /musicbrainz.org\/artist\//);
  await page.locator('.catalog-card').filter({ has: page.getByRole('heading', { name: '19', exact: true }) }).click();
  await expect(page.getByText(/Source edition:/)).toBeVisible();
  await expect(page.getByRole('link', { name: 'MusicBrainz', exact: true })).toHaveAttribute('href', /musicbrainz.org\/release\//);
  await page.locator('.track-list ol li a').first().click();
  await expect(page.getByRole('heading', { name: 'Lyrics unavailable in this catalog.' })).toBeVisible();
  await expect(page.locator('.lyrics-copy')).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'MusicBrainz', exact: true })).toHaveAttribute('href', /musicbrainz.org\/recording\//);
  await page.reload();
  await page.locator('html[data-app-ready="true"]').waitFor();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  expect(pageErrors).toEqual([]);
});

test('the album archive and photo attribution are reachable', async ({ page }) => {
  await page.goto('/discover#album-archive');
  await expect(page.getByRole('heading', { name: 'Inside the album archive' })).toBeVisible();
  await expect(page.locator('#album-archive .catalog-card').first()).toBeVisible();
  await page.goto('/copyright');
  await page.locator('html[data-app-ready="true"]').waitFor();
  await page.getByText('Adele · CC BY 2.0', { exact: true }).click();
  const entry = page.locator('details').filter({ has: page.getByText('Adele · CC BY 2.0', { exact: true }) });
  await expect(entry.locator('a').first()).toHaveAttribute('href', /^https:\/\/commons.wikimedia.org\/wiki\/File:/);
  await expect(entry.getByRole('link', { name: 'License and reuse terms' })).toBeVisible();
});

test('reads the reviewed author lyric edition and retains its source when copied', async ({ page }, testInfo) => {
  await page.goto('/search?q=Poisoning%20Pigeons%20in%20the%20Park&type=songs');
  await page.locator('html[data-app-ready="true"]').waitFor();
  await page.locator('.catalog-card').filter({ hasText: 'More of Tom Lehrer · 1959' }).click();
  await expect(page.getByRole('heading', { level: 1, name: 'Poisoning Pigeons in the Park', exact: true })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section')).toHaveCount(6);
  await expect(page.getByRole('link', { name: 'Read the author’s lyric sheet (PDF)' })).toHaveAttribute('href', /tomlehrersongs.com.*poisoning-pigeons-in-the-park.pdf$/);
  await expect(page.getByRole('link', { name: 'Read the source on Wikisource' })).toHaveCount(0);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => localStorage.setItem('test:copied', text) } }));
  await page.getByRole('button', { name: 'Copy lyrics', exact: true }).click();
  await expect(page.getByText('Lyrics copied', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('test:copied'))).toContain('Public-domain text via Tom Lehrer:');
  await page.getByRole('button', { name: /Verse 6/ }).click();
  await expect(page.locator('#section-6')).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: `test-results/sourced-reader-${testInfo.project.name}.png` });
});

test('reads a complete sourced album and navigates the original section headings', async ({ page }, testInfo) => {
  await page.goto('/albums/tom-lehrer-more-of-tom-lehrer-f1a7e209');
  await page.locator('html[data-app-ready="true"]').waitFor();
  await expect(page.locator('.track-list ol li')).toHaveCount(11);
  await expect(page.locator('.track-list').getByText('Song notes', { exact: true })).toHaveCount(0);
  await page.locator('.track-list').getByRole('link').filter({ hasText: 'Clementine' }).click();
  await expect(page.locator('.lyrics-copy > section')).toHaveCount(4);
  await page.getByRole('button', { name: /IV\. Gilbert and Sullivan/ }).click();
  await expect(page.locator('#section-4')).toBeInViewport();
  await expect(page.locator('#section-4 > span')).toHaveText('IV. Gilbert and Sullivan');
  await expect(page.locator('#section-4 > p').last()).toHaveText('See what I mean?');
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => localStorage.setItem('test:copied', text) } }));
  await page.getByRole('button', { name: 'Copy lyrics', exact: true }).click();
  expect(await page.evaluate(() => localStorage.getItem('test:copied'))).toContain('[IV. Gilbert and Sullivan]');
  await page.reload();
  await page.locator('html[data-app-ready="true"]').waitFor();
  await expect(page.locator('#section-1 > span')).toHaveText('I. Cole Porter');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  await page.locator('#section-1').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/sourced-section-headings-${testInfo.project.name}.png` });
});

test('matches typographic apostrophes and keeps the reviewed source text intact', async ({ page }) => {
  await page.goto('/search?q=She%27s%20My%20Girl&type=songs');
  await page.locator('html[data-app-ready="true"]').waitFor();
  const editions = page.locator('.catalog-card').filter({ has: page.getByRole('heading', { name: 'She’s My Girl', exact: true }) });
  await expect(editions).toHaveCount(4);
  await editions.filter({ hasText: 'More of Tom Lehrer · 1959' }).click();
  await expect(page.locator('.lyrics-copy > section')).toHaveCount(4);
  await expect(page.locator('#section-4 > p').last()).toHaveText('And I love her.');
  await expect(page.getByRole('link', { name: 'Read the author’s lyric sheet (PDF)' })).toHaveAttribute('href', /shes-my-girl.pdf$/);
});

test('reads both parts of New Math from the complete fourteen-track live album', async ({ page }) => {
  await page.goto('/albums/tom-lehrer-that-was-the-year-that-was-c472deda');
  await page.locator('html[data-app-ready="true"]').waitFor();
  await expect(page.locator('.track-list ol li')).toHaveCount(14);
  await expect(page.locator('.track-list .availability--full')).toHaveCount(14);
  await page.locator('.track-list').getByRole('link').filter({ hasText: 'New Math' }).click();
  await expect(page.locator('.lyrics-copy > section')).toHaveCount(14);
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(79);
  await page.getByRole('button', { name: /Verse 14$/ }).click();
  await expect(page.locator('#section-14')).toBeInViewport();
  await expect(page.locator('#section-14 > p').last()).toHaveText('That only a child can do it!');
  await page.reload();
  expect((await page.locator('.lyrics-copy > section > p').allTextContents()).join('\n')).not.toContain('342');
  await expect(page.getByText(/342 - 173 = 169 in base ten/)).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
});

test('retains disc numbers and reads the image-only Alma transcription', async ({ page }, testInfo) => {
  await page.goto('/albums/tom-lehrer-the-remains-of-tom-lehrer-f49a42b9');
  await page.locator('html[data-app-ready="true"]').waitFor();
  const tracks = page.locator('.track-list ol li');
  await expect(tracks).toHaveCount(74);
  await expect(tracks.nth(25).locator('span').first()).toHaveAttribute('aria-label', 'Disc 2, track 1');
  await expect(tracks.nth(49).locator('span').first()).toHaveAttribute('aria-label', 'Disc 3, track 1');
  await tracks.nth(59).getByRole('link').click();
  await expect(page.getByRole('heading', { name: 'Alma', exact: true })).toBeVisible();
  await expect(page.getByText('Disc 3 · Track 11', { exact: true })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(47);
  await page.getByRole('button', { name: /Verse 12$/ }).click();
  await expect(page.locator('#section-12 > p').last()).toHaveText('With Gustav and Walter and Franz!');
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.locator('#section-1').scrollIntoViewIfNeeded();
  await expect(page.getByRole('button', { name: /Verse 1$/, exact: false })).toHaveAttribute('aria-current', 'step');
  await expect(page.getByRole('button', { name: /Verse 1$/, exact: false })).toBeInViewport();
  await page.screenshot({ path: `test-results/sourced-alma-${testInfo.project.name}.png` });
});

test('discovers educational lyrics and searches punctuation variants without losing the source version', async ({ page }, testInfo) => {
  await page.goto('/discover');
  await page.locator('html[data-app-ready="true"]').waitFor();
  await page.getByRole('combobox', { name: 'Theme', exact: true }).selectOption('Learning');
  await page.getByRole('combobox', { name: 'Lyrics', exact: true }).selectOption('full');
  const collection = page.locator('#wordplay-classroom');
  await expect(collection.locator('.catalog-card')).toHaveCount(11);
  await collection.getByRole('link').filter({ hasText: 'N Apostrophe T' }).click();
  await expect(page.getByRole('heading', { level: 1, name: 'N Apostrophe T' })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(51);
  await page.getByRole('button', { name: /The invitation/ }).click();
  await expect(page.locator('#section-3')).toBeInViewport();
  await expect(page.locator('#section-3 > p').last()).toHaveText('Both: N apostrophe T!');
  await page.reload();
  await page.goto('/search?q=L-Y&type=songs');
  await page.locator('.catalog-card').filter({ has: page.getByRole('heading', { name: 'L‐Y', exact: true }) }).click();
  await expect(page.getByRole('heading', { level: 1, name: 'L‐Y', exact: true })).toBeVisible();
  await expect(page.locator('.lyrics-copy > section > p')).toHaveCount(36);
  await expect(page.getByRole('link', { name: 'Read the author’s lyric sheet (PDF)' })).toHaveAttribute('href', /l-y.pdf$/);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact || ''))).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.locator('#section-1').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/sourced-language-${testInfo.project.name}.png` });
});
