import StaticPage from '../components/legal/StaticPage';
import { IMAGE_CREDITS } from '../data/externalCatalog';

export const meta = () => [{ title: 'Copyright and lyric availability — 52lyrics' }, { name: 'description', content: 'How 52lyrics labels original, licensed, public-domain, and unavailable lyric content.' }];

export default function CopyrightPage() {
  return <StaticPage eyebrow="Copyright" title="Availability is a rights decision." intro="A song’s presence in the catalog does not imply permission to reproduce its lyrics.">
    <h2>Availability labels</h2><p>Complete lyrics are available when the catalog records the text as original, licensed, or verified public domain. Public-domain lyrics have their own label and source information. Song notes means 52lyrics displays metadata and original editorial context without reproducing the lyric.</p>
    <h2>Historical texts and attribution</h2><p>Historical lyrics are transcribed from Wikisource. Each entry names its writer, identifies the text edition, and links to a fixed source revision and copyright evidence. Public-domain status refers to the historical words; it does not cover later translations, arrangements, recordings, photographs, or modern adaptations.</p>
    <p>Wikisource identifies its contributed text under <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>, with additional terms for underlying works. We retain this attribution and link to the source. Reading adaptations normalize whitespace, remove printed verse numbers, and label sections; repeated refrains are expanded where noted. The linked terms apply to any protectable transcription contributions, not to the entire site.</p>
    <h2>Original catalog</h2><p>The Midnight Echo, its release concepts, and the lyrics displayed for its ten songs are original content created for this project.</p>
    <h2>Author-released lyrics</h2><p>Tom Lehrer’s complete lyric entries link to the author-published sheet and his <a href="https://tomlehrersongs.com/">November 26, 2022 public-domain declaration</a>. We check displayed transcriptions against the original documents. Text editions may differ from recorded performances; spoken introductions, other writers’ music, and unreviewed source documents are not represented as licensed lyric text.</p>
    <h2>Release metadata</h2><p>Newly sourced artist identities, release editions, recording titles, track positions, and durations are credited to <a href="https://musicbrainz.org/doc/About/Data_License">MusicBrainz core data (CC0)</a>. The catalog does not import MusicBrainz supplementary tags, ratings, or reviews. Existing genre categories and reading notes are editorial contributions by 52lyrics; source-supplied artist styles are credited separately below. Release-data reuse does not grant permission to reproduce song lyrics or album covers.</p>
    <h2>Photographs and image credits</h2><p>Artist photographs are downloaded from Wikimedia Commons and bundled locally. Each photograph retains its own license. Thumbnail sizing and responsive display crops are the only adaptations; no endorsement is implied. Album sleeves remain original 52lyrics abstract illustrations unless separately identified.</p>
    <p>When an artist profile cites Wikidata, its brief description and any source-supplied genre labels come from <a href="https://www.wikidata.org/wiki/Wikidata:Licensing">Wikidata structured data (CC0)</a>. Existing 52lyrics editorial biographies and genre categories are retained. Missing source descriptions or genres are not invented.</p>
    {IMAGE_CREDITS.map((image) => <details key={`${image.wikidataId}-${image.localPath}`} className="image-credit-entry"><summary>{image.name} · {image.license}</summary><p><a href={image.sourceUrl} target="_blank" rel="noreferrer">{image.filename}</a> — {image.attribution || image.author}. <a href={image.licenseUrl} target="_blank" rel="noreferrer">License and reuse terms</a>.</p><p>{image.credit}</p></details>)}
    <h2>Corrections and rights concerns</h2><p>Rights holders can request correction or removal by contacting the site operator through the repository associated with this release.</p>
  </StaticPage>;
}
